import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Clock3, FileText, TrendingUp } from "lucide-react";
import { LmsShell } from "@/components/lms-shell";
import { assignments, courses } from "@/lib/lms-data";

export default function DashboardPage(){ return <LmsShell active="Overview" eyebrow="MONDAY, JULY 21" title="Good morning, Maya.">
  <div className="lms-stat-grid"><article><span><BookOpen size={19}/>ACTIVE COURSES</span><strong>04</strong><small>12 completed modules</small></article><article><span><FileText size={19}/>DUE THIS WEEK</span><strong>06</strong><small>2 require attention</small></article><article><span><TrendingUp size={19}/>GRADE AVERAGE</span><strong>89.4%</strong><small className="positive">↑ 2.1% this term</small></article><article><span><Clock3 size={19}/>LEARNING TIME</span><strong>7.5h</strong><small>This week</small></article></div>
  <div className="lms-two-col"><section className="lms-panel"><div className="panel-head"><div><span>CONTINUE LEARNING</span><h2>Your courses</h2></div><Link href="/courses">View all <ArrowRight size={15}/></Link></div><div className="course-list">{courses.slice(0,3).map(c=><Link href="/courses" className="course-row" key={c.code}><i className={c.color}/><div><small>{c.code}</small><strong>{c.title}</strong><span>{c.next}</span></div><div className="row-progress"><span>{c.progress}%</span><div><i style={{width:`${c.progress}%`}}/></div></div><ArrowRight size={17}/></Link>)}</div></section>
  <aside className="lms-panel"><div className="panel-head"><div><span>UPCOMING</span><h2>Deadlines</h2></div><CalendarDays size={19}/></div><div className="deadline-list">{assignments.slice(0,3).map((a,i)=><div key={a.title}><span><b>{i===0?"21":"22"}</b>JUL</span><div><small>{a.course}</small><strong>{a.title}</strong><em>{a.due}</em></div></div>)}</div><Link className="panel-link" href="/assignments">Open all assignments <ArrowRight size={15}/></Link></aside></div>
  <section className="announcement"><span>ANNOUNCEMENT</span><div><strong>Welcome to the summer term</strong><p>Review your course syllabi and confirm notification preferences before Friday.</p></div><small>2 HOURS AGO</small></section>
  </LmsShell> }
